### ISSUE TITLE
playbook PostgreSQLDatabaseCreate.yml failed

### ISSUE THREAD

**Issue by yungezz** [Azure-Samples/ansible-playbooks#11]
> Please provide us with the following information:
> ---------------------------------------------------------------
error is:
```
Still running (2 of 50): ansible-playbook ./PostgreSQLDatabaseCreate.yml --extra-vars {"azure_subscription_id":[secure],"azure_tenant":[secure],"azure_client_id":[secure]}
The command ansible-playbook ./PostgreSQLDatabaseCreate.yml --extra-vars {"azure_subscription_id":[secure],"azure_tenant":[secure],"azure_client_id":[secure]} exited with 2.
Log:
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source
 [WARNING]: No inventory was parsed, only implicit localhost is available
 [WARNING]: provided hosts list is empty, only localhost is available. Note
that the implicit localhost does not match 'all'
PLAY [localhost] ***************************************************************
TASK [Gathering Facts] *********************************************************
ok: [localhost]
TASK [Azure.azure_preview_modules : debug] *************************************
skipping: [localhost]
TASK [Create a resource group] *************************************************
changed: [localhost]
TASK [Create PostgreSQL Server] ************************************************
 [WARNING]: Azure API profile latest does not define an entry for
PostgreSQLManagementClient
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating the PostgreSQL Server instance: Azure Error: InvalidEditionSloCombination\nMessage: The edition Basic does not support the service objective PGSQLS100"}
	to retry, use: --limit @/home/travis/build/Azure-Samples/ansible-playbooks/PostgreSQLDatabaseCreate.retry
PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1   
```
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by zikalino** [comment]
This is actually Ansible dependency error, not a sample error.
It can't be fixed in a sample, it's already fixed in Ansible devel branch.
This could be fixed by referring to our role in the test...

**Comment by yungezz** [comment]
@zikalino what does 'should be fixed now' mean? Code fixed in role side? pls run this playbook against latest role and ansible bits, then close the issue if succeeded.

**Comment by yaweiw** [comment]
if it's verified then just go ahead close the issue.

**Comment by zikalino** [comment]
@yaweiw @yungezz i would like to see it verified by ci before i close it.

**Comment by yungezz** [comment]
@zikalino as we offline synced, pls verify this playbook by yourself, then close the issue if it passed.

As mentioned in email, currently CI on this playbook sample repo is only enabled on master branch, weekly run. It's not enabled for PR because:
1. this repo is sample playbook repo. We're not targeting to test binaries by this repo, but verifying playbooks, and weather they're working with latest ansible binaries and role bits.
2. it's unnecessary to run CI which covers all playbooks in this repo per PR, because it just sample and time-consuming. If user create/update a playbook, just verify it by themselves, then check in.
