### ISSUE TITLE
ACICreatewithACR.yml failed because of no package docker-py

### ISSUE THREAD

**Issue by yungezz** [Azure-Samples/ansible-playbooks#23]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>
```
TASK [Login docker registry] ***************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import docker-py - No module named docker. Try `pip install docker-py`"}
	to retry, use: --limit @/home/travis/build/Azure-Samples/ansible-playbooks/ACIcreatewithACR.retry
```

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by zikalino** [comment]
# Prequisite

# ===========

# - git

# - Docker

The prerequisites state that docker should be installed. What else should we do?

**Comment by yungezz** [comment]
in ci environemtn, install git and  docker.
