### ISSUE TITLE
CI doesn't pick up samples located in subdirectories

### ISSUE THREAD

**Issue by zikalino** [Azure-Samples/ansible-playbooks#30]
All the samples located in subdirectories are ignored.
I suggest that CI should read a file with list of samples that should be tested, as just scanning for "yml" files may be not ideal solution.
Some yml files may be nor exactly samples.
In case of some tests (these in subdirectories), samples should be executed in particular sentence.

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
run tests
check if any sample from subdirectory was run

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by yungezz** [comment]
PR #38
