### ISSUE TITLE
Documentation not clear for create_virtualmachine_with_subnet_in_different_resource_group

### ISSUE THREAD

**Issue by zikalino** [Azure-Samples/ansible-playbooks#49]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Try to use create_virtualmachine_with_subnet_in_different_resource_group sample

It's very unclear how it should be used and how to set up your Ansible environment so it runs correctly.
I figured out users should run Ansible on the VM that belongs to particular virtual network, and sample should create VM in the same VN. But it's not clear. 

### Any log messages given by the failure
no log

### Expected/desired behavior
doc should be very clear about prerequisites

### Versions
2.7

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Fred-sun** [comment]
@zikalino
