### ISSUE TITLE
Ansible playbook error vm_create_windows.yml

### ISSUE THREAD

**Issue by dennopro** [Azure-Samples/ansible-playbooks#78]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> edited playbook with resource group name as Ansible then run playbook vm_create_windows.yml in ansible

### Any log messages given by the failure
>
TASK [create Azure virtual network in resource group] **************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'Ansible' is undefined\n\nThe error appears to be in '/var/lib/awx/projects/_14__azure_infrastructure_test/vm_create_windows.yml': line 33, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: create Azure virtual network in resource group\n    ^ here\n"}

### Expected/desired behavior
>
success creation of virtual network 
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
ansible is on linux, linked azure to ansible and was to create a windows server 2016 in azure
### Versions
>
Ansible 2.8
### Mention any other details that might be useful
adding existing resource group fails, creating new resource group also fails
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Fred-sun** [comment]
@dennopro Thank you for taking the time to report this problem! It is known from your error message that an unknown variable caused the error. Can you provide your playbook for me to try? Thank you very much!

**Comment by dennopro** [comment]
Hello Fred,

I managed to fix this by renaming the resource group declared variable in
the playbook form "{{resource_group}}"" to "resource_group" this was in the
play book vm_create_windows.yml
and this worked out well, thanx for the followup

regards

Andrew

**Comment by Fred-sun** [comment]
@dennopro Ok, thank you for your reply. If there is no other problem, can this problem be closed?

**Comment by dennopro** [comment]
This can be closed

Regards


Andrew

**Comment by Fred-sun** [comment]
close_me

**Comment by Fred-sun** [comment]
ping to close

**Comment by dennopro** [comment]
thanx for the ping fred, sorry been away for a while
